package demo.entity;

// Generated 2015-5-27 16:42:53 by Hibernate Tools 3.4.0.CR1

/**
 * Mydemo generated by hbm2java
 */
public class Mydemo implements java.io.Serializable {

	private Integer id;
	private Userclass userclass;
	private String name;
	private String sex;
	private String password;

	public Mydemo() {
	}

	public Mydemo(Userclass userclass, String password) {
		this.userclass = userclass;
		this.password = password;
	}

	public Mydemo(Userclass userclass, String name, String sex, String password) {
		this.userclass = userclass;
		this.name = name;
		this.sex = sex;
		this.password = password;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Userclass getUserclass() {
		return this.userclass;
	}

	public void setUserclass(Userclass userclass) {
		this.userclass = userclass;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
