package demo.entity;

// Generated 2015-5-27 16:42:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

/**
 * Paper generated by hbm2java
 */
public class Paper implements java.io.Serializable {

	private Integer id;
	private Station station;
	private String papername;
	private Integer papermaker;
	private String makedate;
	private String memo;
	/*private Set testquestions = new HashSet(0);*/
	private Set testquestions = new TreeSet();

	public Paper() {
	}

	public Paper(String papername) {
		this.papername = papername;
	}

	public Paper(Station station, String papername, Integer papermaker,
			Set testquestions) {
		this.station = station;
		this.papername = papername;
		this.papermaker = papermaker;
		this.testquestions = testquestions;
	}

	public Paper(Station station, String papername,
			Integer papermaker, String makedate, String memo, Set testquestions) {
		this.station = station;
		this.papername = papername;
		this.papermaker = papermaker;
		this.makedate = makedate;
		this.memo = memo;
		this.testquestions = testquestions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	public String getPapername() {
		return this.papername;
	}

	public void setPapername(String papername) {
		this.papername = papername;
	}

	public Integer getPapermaker() {
		return this.papermaker;
	}

	public void setPapermaker(Integer papermaker) {
		this.papermaker = papermaker;
	}
	
	public String getMakedate() {
		return makedate;
	}

	public void setMakedate(String makedate) {
		this.makedate = makedate;
	}
	
	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Set getTestquestions() {
		return testquestions;
	}

	public void setTestquestions(Set testquestions) {
		this.testquestions = testquestions;
	}

}
