package demo.entity;

// Generated 2015-5-27 16:42:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Questiontype generated by hbm2java
 */
public class Questiontype implements java.io.Serializable {

	private Integer id;
	private String type;
	private int ischoose;
	private Integer anwsercount;
	private int isjudge;
	private Set testquestionses = new HashSet(0);

	public Questiontype() {
	}

	public Questiontype(int ischoose) {
		this.ischoose = ischoose;
	}
	
	public Questiontype(int ischoose, int isjudge) {
		this.ischoose = ischoose;
		this.isjudge = isjudge;
	}

	public Questiontype(Integer id, String type, int ischoose,
			Integer anwsercount, int isjudge, Set testquestionses) {
		super();
		this.id = id;
		this.type = type;
		this.ischoose = ischoose;
		this.anwsercount = anwsercount;
		this.isjudge = isjudge;
		this.testquestionses = testquestionses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public int getIsjudge() {
		return isjudge;
	}

	public void setIsjudge(int isjudge) {
		this.isjudge = isjudge;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getIschoose() {
		return this.ischoose;
	}

	public void setIschoose(int ischoose) {
		this.ischoose = ischoose;
	}

	public Integer getAnwsercount() {
		return this.anwsercount;
	}

	public void setAnwsercount(Integer anwsercount) {
		this.anwsercount = anwsercount;
	}

	public Set getTestquestionses() {
		return this.testquestionses;
	}

	public void setTestquestionses(Set testquestionses) {
		this.testquestionses = testquestionses;
	}

}
