package demo.entity;

// Generated 2015-5-27 16:42:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Testquestions generated by hbm2java
 */
public class Testquestions implements java.io.Serializable,Comparable<Testquestions> {
	private Integer id;
	private Station station;
	private Questiontype questiontype;
	private String questionname;
	private String correct;
	private String questionoption;
	private Set papers = new HashSet(0);

	public Testquestions() {
	}

	public Testquestions(String questionname, String correct,
			String questionoption) {
		this.questionname = questionname;
		this.correct = correct;
		this.questionoption = questionoption;
	}

	public Testquestions(Station station, Questiontype questiontype,
			String questionname, String correct, String questionoption) {
		super();
		this.station = station;
		this.questiontype = questiontype;
		this.questionname = questionname;
		this.correct = correct;
		this.questionoption = questionoption;
	}

	public Testquestions(Station station, Questiontype questiontype,
			String questionname, String correct, String questionoption,
			Set papers) {
		this.station = station;
		this.questiontype = questiontype;
		this.questionname = questionname;
		this.correct = correct;
		this.questionoption = questionoption;
		this.papers = papers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	public Questiontype getQuestiontype() {
		return this.questiontype;
	}

	public void setQuestiontype(Questiontype questiontype) {
		this.questiontype = questiontype;
	}

	public String getQuestionname() {
		return this.questionname;
	}

	public void setQuestionname(String questionname) {
		this.questionname = questionname;
	}

	public String getCorrect() {
		return this.correct;
	}

	public void setCorrect(String correct) {
		this.correct = correct;
	}

	public Set getPapers() {
		return papers;
	}

	public void setPapers(Set papers) {
		this.papers = papers;
	}

	public String getQuestionoption() {
		return questionoption;
	}
	
	public void setQuestionoption(String questionoption) {
		this.questionoption = questionoption;
	}

	@Override
	public int compareTo(Testquestions o) {
		if(this.getQuestiontype().getId()>o.getQuestiontype().getId()){
			return 1;
		}
		return -1;
	}
}
